Added support for checking whether /dev/tty1 is present.

diff --git a/gentoo/splash b/gentoo/splash
--- a/gentoo/splash
+++ b/gentoo/splash
@@ -83,16 +83,26 @@ if [ "$1" == "start" ]; then
 	# Display a warning if the system is not configured to display init messages
 	# to tty1. This can cause a lot of problems if it's not handled correctly, so
 	# we don't allow silent splash to run on incorrectly configured systems.
-	if [[ -z "`grep 'CONSOLE=/dev/tty1' /proc/cmdline`" && 
-		  -z "`grep 'CONSOLE=/dev/vc/1' /proc/cmdline`" ]]; then
-		if [[ ${SPLASH_MODE_REQ} == "silent" ]]; then
+	if [[ ${SPLASH_MODE_REQ} == "silent" ]]; then
+		if [[ -z "`grep 'CONSOLE=/dev/tty1' /proc/cmdline`" ]]; then
+			clear
 			ewarn "You don't appear to have a correct CONSOLE= setting on your kernel"
-			ewarn "command line. Silent splash will not be enabled. Please add either"
-			ewarn "CONSOLE=/dev/tty1 or CONSOLE=/dev/vc/1 to your kernel command line"
-			ewarn "to avoid this message."
-			${SPLUTIL} -c on 2>/dev/null
+			ewarn "command line. Silent splash will not be enabled. Please add"
+			ewarn "CONSOLE=/dev/tty1 to your kernel command line to avoid this message."
+			exit 1
 		fi
-		exit 1
+
+		mount --bind / ${spl_tmpdir}
+		if [[ ! -c "${spl_tmpdir}/dev/tty1" ]]; then
+			umount ${spl_tmpdir}
+			clear
+			ewarn "The filesystem mounted on / doesn't contain the /dev/tty1 device"
+			ewarn "which is required for the silent splash to function properly."
+			ewarn "Silent splash will not be enabled. Please create the appropriate"
+			ewarn "device file to avoid this message."
+			exit 1
+		fi
+		umount ${spl_tmpdir}
 	fi
 
 	# In the unlikely case that there's a splash daemon running -- kill it.
