debian: use centralized functions fbcondecor_supported, fbcondecor_set_theme, implement last error cond-file, made a bgsetup section (used by /etc/init.d/splashutilsend), use log_ functions from lsb

diff --git a/debian/splashutils.init b/debian/splashutils.init
--- a/debian/splashutils.init
+++ b/debian/splashutils.init
@@ -3,19 +3,7 @@
 . /lib/lsb/init-functions
 . /sbin/splash-functions.sh
 
-spl_decor="/sbin/fbcondecor_ctl"
-spl_fbsupport=0
-
-check_fbsupport()
-{
-    if [ -e /dev/fbsplash ] && [ -e /proc/fbsplash -o -e /proc/sys/kernel/fbsplash ]; then
-        spl_fbsupport=1
-    fi
-    
-    if [ -e /dev/fbcondecor ] && [ -e /proc/fbsplash -o -e /proc/sys/kernel/fbcondecor ]; then
-        spl_fbsupport=1
-    fi
-}
+spl_lasterror="/lib/splash/cache/lasterror"
 
 #
 ## Prevent killall5 of fbsplashd.static
@@ -62,22 +50,33 @@ splash_update_omit()
     fi
 }
 
-splash_setup
+#
+## Set a theme on a tty
+#
+set_theme()
+{
+    ${spl_decor} --tty="${2}" -t "${1}" -c setcfg || return 1
+    ${spl_decor} --tty="${2}" -t "${1}" -c setpic -q
+    ${spl_decor} --tty="${2}" -c on || return 1
+    
+    return 0
+}
 
 case "$1" in
-    start)
-	check_fbsupport
-	
-	splash rc_init sysinit
-	
+
+    bgsetup)
         # only do this if the kernel supports fbsplash
-	if [ ${spl_fbsupport} -eq 1 ]; then
+	if fbcondecor_supported ; then
 	    
             if [ -z "${SPLASH_TTYS}" ]; then
                 if [ -n "${RC_TTY_NUMBER}" ]; then	
-                    SPLASH_TTYS=$(seq 0 "${RC_TTY_NUMBER}")
+                    SPLASH_TTYS=$(seq 1 "${RC_TTY_NUMBER}")
                 else
-                    SPLASH_TTYS="0 1 3 4 5 6"
+                    if [ "x$2" != "x" ]; then
+                        $SPLASH_TTYS=$2
+                    else
+                        SPLASH_TTYS="1 2 3 4 5 6"
+                    fi
                 fi
             fi
 
@@ -85,12 +84,12 @@ case "$1" in
 	    for TTY in ${SPLASH_TTYS} ; do
 		theme="${SPLASH_THEME}"
 		
-		[[ ${TTY} == "1" && -z "$(${spl_decor} -c getstate --tty=${TTY}| grep 'off')" ]] && continue
-		[[ ${TTY} == "0" ]] && continue
-		
-		if [[ -n "${SPLASH_TTY_MAP}" ]]; then
+                [ ${TTY} = "1" -a -z "$(${spl_decor} -c getstate --tty=${TTY}| grep 'off')" ] && continue
+                [ ${TTY} = "0" ] && continue
+
+                if [ -n "${SPLASH_TTY_MAP}" ]; then
 		    for i in ${SPLASH_TTY_MAP} ; do
-			if [[ "${i%:*}" == "${TTY}" ]]; then
+                        if [ "${i%:*}" = "${TTY}" ]; then
 			    theme="${i#*:}"
 			fi
 		    done
@@ -99,29 +98,61 @@ case "$1" in
                 #
                 ## openvt is in the console-tools package
                 #
-		if [[ -x /usr/bin/openvt ]]; then
-		    /usr/bin/openvt -c ${TTY} echo -n "" 2>/dev/null
+		if [ -x /usr/bin/openvt ]; then
+		    /usr/bin/openvt -c ${TTY} -- printf "" 2>/dev/null
 		fi
 		
-		[[ -z "$(${spl_decor} -c getstate --tty=${TTY} 2>/dev/null| grep 'off')" && -n "$(${spl_decor} -c getcfg --tty=${TTY} 2>/dev/null| grep ^theme:[[:space:]]*${theme}$)" ]] && continue
-		${spl_decor} --tty="${TTY}" -m v -t "${theme}" -c setcfg 2>/dev/null 
-		${spl_decor} --tty="${TTY}" -m v -t "${theme}" -c setpic 2>/dev/null
-		${spl_decor} --tty="${TTY}" -c on 2>/dev/null
+                if ! fbcondecor_set_theme "${theme}" "${TTY}"; then
+                    if [ -z "${FBCONDECOR_TTY_MAP}" ]; then
+                        log_warning_msg "Failed to set background image on tty${TTY}"
+                        break
+                    fi
+                fi
+
 	    done
-	    #
-	    ## Prevent killall5 of fbsplashd.static
-	    #
-	    splash_add_omit
 	else
             # echo "Your kernel does not support fbcondecor"
 	    exit 1
 	fi
 	;;
     
+    start)
+        log_daemon_msg "Starting splashutils daemon" "fbsplashd.static"
+
+        # only do this if the kernel supports fbsplash
+	if fbcondecor_supported ; then
+	    
+            splash_setup
+            splash rc_init sysinit
+
+            $0 status
+            spl_status=$?
+            if [ $spl_status -ne 0 ]; then
+                log_end_msg 1
+                exit $spl_status
+            fi
+            #
+            ## Initialize backgrounds
+            #
+            $0 bgsetup
+
+	    #
+	    ## Prevent killall5 of fbsplashd.static
+	    #
+	    splash_add_omit
+
+            log_end_msg 0
+	else
+            log_failure_msg "Your kernel does not support fbcondecor"
+            log_end_msg 1
+	    exit 1
+	fi
+	;;
+    
     status)
 	pidofproc fbsplashd.static >/dev/null
-	status=$?
-	exit $status
+	spl_status=$?
+	exit $spl_status
 	;;
     
     restart)
@@ -131,9 +162,20 @@ case "$1" in
     
     condrestart)
 	$0 status
-	if [ $? -ne 0 ]; then
+	spl_status=$?
+	if [ $spl_status -ne 0 -a ! -s $spl_lasterror ]; then
+            #
+            ## Make sure the cache is clean in any case
+            #
             splash_cache_cleanup
             $0 start
+            $0 status
+            if [ $? -ne 0 ]; then
+                touch $spl_lasterror && echo "`date` : failed to start" >> $spl_lasterror
+		exit 1
+	    fi
+        elif [ $spl_status -ne 0 ]; then
+            exit 1
         fi
 	;;
     
@@ -143,30 +185,41 @@ case "$1" in
 	;;
     
     stop)
-	#
-	## Remove prevention against killall5
-	#
-        splash_remove_omit
-	splash_exit
+	$0 status
+	if [ $? -eq 0 ]; then
+	    #
+	    ## Remove prevention against killall5
+	    #
+            splash_remove_omit
+            splash_exit
+        fi
+        #
+        ## Force again cache cleanup in any case
+        #
+        splash_cache_cleanup
 	;;
     
     progress)
         $0 condrestart
-        splash_update_omit
-	splash_comm_send "progress ${2}"
-	splash_comm_send "paint"
+        if [ $? -eq 0 ]; then
+            splash_update_omit
+            splash_comm_send "progress ${2}"
+            splash_comm_send "paint"
+        fi
 	;;
     
     PROGRESS)
         $0 condrestart
-        splash_update_omit
-        value=${2}
-	if [ ${value} -lt 0 ]; then
-	    value=$[-${value}]
-	fi
-	value=$((${value} * 65535 / 100))
-	splash_comm_send "progress ${value}"
-	splash_comm_send "paint"
+        if [ $? -eq 0 ]; then
+            splash_update_omit
+            value=${2}
+            if [ ${value} -lt 0 ]; then
+                value=$[-${value}]
+            fi
+            value=$((${value} * 65535 / 100))
+            splash_comm_send "progress ${value}"
+            splash_comm_send "paint"
+        fi
 	;;
     
     *)
